### ISSUE TITLE
WASM

### ISSUE THREAD

**Issue by mberry** [Argyle-Software/dilithium#1]
Add a wasm api and package for publishing to npm

**Comment by Axel07l** [comment]
Hi, I add the wasm support for Dilithium. Can you give me some feedback.

[Dilithium](https://github.com/Axel07l/dilithium)

Thanks

**Comment by mberry** [comment]
Looks good, not seeing any errors. I'll run it through the test vectors tomorrow, feel free to submit a PR. 

Perhaps also put a wasm section in readme and add wasm to the features table? eg.

## Wasm

[How to build with wasm-pack ] `wasm-pack build -- --features wasm`

[Basic usage in js] ...

**Comment by mberry** [comment]
Closed with #12
